import Head from "next/head";

import Navbar from "../components/Navbar";
import Room from "../components/room/Room";

import { useSelector } from "react-redux";

import { getRooms } from "../redux/actions/roomsActions";
import { wrapper } from "../redux/store";

export default function Home() {
  const { rooms } = useSelector((state) => state.allRooms);
  return (
    <div>
      <Head>
        <title>Travigo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Monda:wght@400;700&family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <section className="container mx-auto p-4 font-inter">
        <Navbar />
        <Room rooms={rooms} />
      </section>
    </div>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  async ({ req, store }) => {
    await store.dispatch(getRooms(req));
  }
);
